# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Gradle Plugins
loom_version=1.17.5
grgit_version=5.0.0
github_api_version=1.314

# Mod Properties
mod_version=2.5.0+26.1.2
maven_group=me.ngcsonsplash.serverseasons

# Fabric Properties
minecraft_version=26.1.2
yarn_mappings=26.1.2+official
loader_version=0.19.3

# Fabric API
fabric_version=0.151.0+26.1.2

#Libraries
modmenu_version=18.0.0-beta.1
jei_version=29.5.0.26

#Publishing
curseforge_id=413523
modrinth_id=KJe6y9Eu
